always-run: 
  tags: [cori-login]
  script: 
    - echo 'this should run on pull requests'
    - whoami
    - hostname -f
    - git remote -v    
    - git branch
    - ls -l
    - source setup.sh
    - python --version
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -m

on-pull-requests:
  tags: [cori-login]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"'
      when: always
    
  script: 
    - echo 'this should run on pull requests'
    - whoami
    - git remote -v
    - git branch
    - ls -l 
    - source setup.sh
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -m
