always-run: 
  tags: [cori-login]
  script: 
    - echo 'this should run on pull requests'
    - whoami
    - cd buildtest
    - git remote -v
    - git branch
    - source setup.sh
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -mecho 'this should always run'

on-pull-requests:
  tags: [cori-login]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
      when: 'always'
  script: 
    - echo 'this should run on pull requests'
    - whoami
    - cd buildtest
    - git remote -v
    - git branch
    - source setup.sh
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -m
