on-pull-requests_rules:
  tags: ["cori-login"]
  # tags: ["runner:shell"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "pull_request" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH == "devel"'
      when: always
      changes:
        - buildtest/*
    
  script: 
    - module load python    
    - echo "$CI_PIPELINE_SOURCE"
    - whoami
    - git branch
    - conda env create -n buildtest python=3.8
    - source activate buildtest    
    - source setup.sh
    - pip install -r docs/requirements.txt
    - coverage run -m pytest -vra tests
    - conda env remove -n buildtest -y
