
always-run:
  tags: [cori-login]
  script: 
    - echo 'this should always run'
    - pwd && ls -l
    - cd buildtest
    - /usr/bin/git rev-parse HEAD
    - git remote -v
    - git branch
on-pull-requests:
  tags: [cori-login]
  script: 
    - echo 'this should run on pull requests'
    - pwd && ls -l
    - cd buildtest
    - git rev-parse HEAD
    - git remote -v
    - git branch
  only:
    - external_pull_requests
