stages:
  - test
pr_cori_test:
  tags:
    - cori-login
  stage: test
  script:
    - pwd && ls -l
    - hostname
    - cd buildtest
    - git rev-parse HEAD
    - source setup.sh
    - buildtest --version
    
    
