run_always:
  tags: [cori-login]   
  script: 
    - echo "$CI_PIPELINE_SOURCE"
    - whoami
    - git remote -v
    - git branch
    - ls -l 
    - source setup.sh
    - buildtest --help 
    - which buildtest
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -m


on-pull-requests:
  tags: [cori-login]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: always
    
  script: 
    - echo "$CI_PIPELINE_SOURCE"
    - echo 'this should run on pull requests'
    - whoami
    - git remote -v
    - git branch
    - ls -l 
    - source setup.sh
    - buildtest --help 
    - pip install -r docs/requirement.txt
    - coverage run -m pytest -vra tests
    - coverage report -m
