language: python
dist: xenial
arch:
  - amd64
python:
  - 3.6
  - 3.7
  - 3.8
git:
  quiet: true
branches:
  only:
    - devel
env:
  matrix:
    - LMOD_VERSION=6.6.2
    - LMOD_VERSION=7.8.2
addons:
  apt:
    packages:
      # install Lmod Deps
      - lua-filesystem
      - lua-json
      - lua-posix
      - lua-term
      - lua5.2
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install python-coveralls
  - pip install easybuild
  - pip install -r docs/requirements.txt
  - source $TRAVIS_BUILD_DIR/buildtest/scripts/install_deps.sh $LMOD_VERSION

before_script:
  - type module
  - module --version
  - export EASYBUILD_PREFIX=/opt/easybuild
  - mkdir -p $EASYBUILD_PREFIX
  - eb --version
  - eb M4-1.4.17.eb bzip2-1.0.6.eb --robot

script:
  - module use $EASYBUILD_PREFIX/modules/all/
  - module use $LMOD_PKG/modulefiles/Core
  - echo $MODULEPATH
  - cd $TRAVIS_BUILD_DIR
  - source sourceme.sh
  - coverage run -m pytest -v -rP tests/
  - coverage report -m

after_success:
  - codecov
  - coveralls
