language: python
dist: xenial
arch:
  - amd64
python:
  - 3.6
  - 3.7
  - 3.8
git:
  quiet: true
branches:
  only:
    - devel
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install coveralls
  - pip install -r docs/requirements.txt

script:
  - cd $TRAVIS_BUILD_DIR
  - source setup.sh
  - coverage run -m pytest -vrP tests/
  - coverage report -m

after_success:
  - codecov
  - coveralls
