executors:
  local:
    bash_shell:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh_shell:
      description: submit jobs on local machine using sh shell
      shell: sh

    python_shell:
      description: submit jobs on local machine using python shell
      shell: python
  ssh:
    localhost:
      host: localhost
      user: siddiq90
      identity_file: ~/.ssh/id_rsa
  slurm:
    haswell:
      options: ["-C haswell"]
      launcher: sbatch
config:
  editor: vi
  paths:
    prefix: /tmp
    clonepath: /tmp
    searchpath: /tmp
    logdir: /tmp
    testdir: /tmp