name: TutorialsValidation

on:
  pull_request:
    branches: [ devel ]


jobs:

  buildtest-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
   
   
    - name: Get buildtest
      run: |
        git --version
        pip install -U pip
        git fetch -u origin devel:devel
        python --version
        pip install -e .
        which buildtest
        buildtest --version
        buildtest --help
   
    - name: Find buildspecs
      run: buildtest buildspec find
    
    - name: Buildspec Features
      run: |

        buildtest buildspec find --tags
        buildtest buildspec find --list-executors
        buildtest buildspec find --clear
        buildtest buildspec view exit1_pass
    
    - name: Filter buildspec cache
      run: | 
        buildtest buildspec find --helpfilter
        buildtest buildspec find --filter tags=fail
        buildtest buildspec find --filter tags=compiler,executor=local.bash
        buildtest buildspec find --filter type=script,executor=local.bash,tags=tutorials
    
    - name: Running Tutorials Example
      run: buildtest build -b tutorials/
    
    - name: build examples
      run: | 
        buildtest build --tags fail
        buildtest build --tags fail --tags compiler
        buildtest build --executor local.sh
        buildtest build --tags tutorials --executor local.sh
        buildtest build -b tutorials/compilers -x tutorials/compilers/vecadd.yml --tags fail 
        buildtest build -b tutorials --executor local.sh
        
    - name: Checking Test Reports
      run: | 
        buildtest report
        buildtest report --filter buildspec=tutorials/pass_returncode.yml --format name,state,buildspec
        buildtest report --filter name=exit1_pass --format id,returncode,state,runtime
        buildtest report --filter state=PASS,executor=local.bash --format id,state,executor
        
    - name: Test Configuration 
      run: |
        buildtest config validate
        buildtest config view
        buildtest config summary
        
    - name: Test Schemas
      run: |
        buildtest schema
        buildtest schema -n global.schema.json --json
        buildtest schema -n settings.schema.json --json
        buildtest schema -n script-v1.0.schema.json --json
        buildtest schema -n compiler-v1.0.schema.json --json
        buildtest schema -n global.schema.json --example
        buildtest schema -n settings.schema.json --example
        buildtest schema -n script-v1.0.schema.json --example
        buildtest schema -n compiler-v1.0.schema.json --example
        
        
        
      
