# This is a basic workflow to help you get started with Actions

name: TutorialsValidation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
   
   
    - name: Get buildtest
      run: |
        git --version
        pip install -U pip
        git fetch -u origin devel:devel
        python --version
        pip install -e .
        which buildtest
        buildtest --version
        buildtest --help
   
    - name: Validate buildspecs in tutorials
      run: |
        buildtest buildspec find
    
    - name: Running Tutorials Example
      run: |
        buildtest build -b tutorials/
        buildtest build -b tutorials/ -x tutorials
    
    - name: Checking Test Reports
      run: | 
        buildtest report
        buildtest report --filter buildspec=tutorials/pass_returncode.yml --format name,state,buildspec
        buildtest report --filter name=exit1_pass --format id,returncode,state,runtime
        buildtest report --filter state=PASS,executor=local.bash --format id,state,executor
      
    - name: Buildspec Features
      run: |
        buildtest buildspec find --tags
        buildtest buildspec find --list-executors
        buildtest buildspec find --clear
        
    - name: Test Configuration 
      run: |
        buildtest config validate
        buildtest config view
        buildtest config summary
        
    - name: Test Schemas
      run: |
        buildtest schema
        buildtest schema -n global.schema.json --json
        buildtest schema -n script-v1.0.schema.json --json
        buildtest schema -n compiler-v1.0.schema.json --json
        buildtest schema -n setting.schema.json --json
        buildtest schema -n global.schema.json --examples
        
        
      
