name: regressiontest

on:
  pull_request:
    branches: [ devel ]

jobs:

  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]


    steps:

    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
  
   
    - name: test-buildtest
      run: |
        sudo apt-get install -y tcsh zsh
        source setup.sh
        pip install pytest
        pip install coverage 
        coverage run -m pytest -vra tests
        coverage report -m
        ls -l .coverage htmlcov

        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true 
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}

