name: Check URLs

on: [push, pull_request]

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - name: URLs-checker
      uses: SuperKogito/URLs-checker@0.1.4
      with:
        # The project base path.
        git_path: https://github.com/HPC-buildtest/buildtest-framework

        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.rst

        # Choose whether to include file with no URLs in the prints.
        print_all: False

        white_listed_urls: "https://github.com/marketplace/trafico-pull-request-labeler,https://github.com/HPC-buildtest/buildtest-framework,https://easybuild.readthedocs.io/en/latest/,https://github.com/HPC-buildtest/buildtest-framework/issues,https://buildtest.readthedocs.io/en/latest/index.html"
