name: Check URLs

on: [push, pull_request]

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: URLs-checker
      uses: urlstechie/URLs-checker@add/checkout-optional-git-path
      with:
        # check this subfolder only
        subfolder: docs

        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.rst

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3

        # Cannot check private GitHub settings
        white_listed_patterns: https://github.com/HPC-buildtest/buildtest-framework/settings
